### ISSUE TITLE
Table Service not accepting Annotations option

### ISSUE THREAD

**Issue by rajat23495** [door2door-io/osrm-express-server-demo#8]
This is in reference to table.js file, it gives only duration matrix, when i tried adding annotations parameter or options it says unexpected identifier
```
const express = require("express");
const logfmt = require("logfmt");

const router = express.Router();

router.post("/", (req, res) => {
  if (!req.body.coordinates) {
    return res.status(422).json({ error: "Missing coordinates" });
  }

  const osrm = req.app.get("osrm");
  const options = {
    coordinates: req.body.coordinates,
    sources: req.body.sources,
    destinations: req.body.destinations
    annotations: ['duration','distance']
  };

  if (!req.body.sources || !req.body.destinations) {
    delete options.sources;
    delete options.destinations;
  }

  try {
    osrm.table(options, (err, result) => {
      if (err) {
        return res.status(422).json({ error: err.message });
      }
      return res.json(result);
    });
  } catch (err) {
    logfmt.error(new Error(err.message));
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
```

error - 
```
yarn run v1.17.3
$ node src/run.js
/usr/src/app/src/routes/table.js:16
    annotations: ['duration','distance']
    ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/src/app/src/app.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by quiqua** [comment]
The code is missing a `comma` here:
```
estinations: req.body.destinations <- missing comma
annotations: ['duration','distance']
```
